"use client";
import {useEffect,useState} from "react";
import {Shell} from "@/components/LuvimosUI";

type Mode="focus"|"memory";
export default function Games(){const [mode,setMode]=useState<Mode>("focus");const [score,setScore]=useState(0);const [target,setTarget]=useState(30);const [time,setTime]=useState(30);const [sequence,setSequence]=useState<number[]>([1,2,3]);const [next,setNext]=useState(1);const [message,setMessage]=useState("Tap the glowing target as fast as you can.");
useEffect(()=>{if(time<=0)return;const id=setInterval(()=>setTime(t=>t-1),1000);return()=>clearInterval(id)},[time]);
const reset=()=>{setScore(0);setTime(30);setNext(1);setSequence(Array.from({length:3},()=>1+Math.floor(Math.random()*9)));setMessage(mode==='focus'?"Fresh round. Find the target.":"Tap the numbers in order.")};
const hitFocus=()=>{if(time<=0)return;setScore(s=>s+1);setTarget(8+Math.floor(Math.random()*84));setMessage("Nice. Keep your attention here.")};
const hitMemory=(n:number)=>{if(time<=0)return;if(n===sequence[next-1]){if(next===sequence.length){setScore(s=>s+1);setSequence(Array.from({length:sequence.length+1},()=>1+Math.floor(Math.random()*9)));setNext(1);setMessage("Sequence cleared. It gets harder now.")}else setNext(nxt=>nxt+1)}else{setNext(1);setMessage("Reset and try the sequence again.")}};
return <Shell><main className="mx-auto max-w-6xl px-5 py-14 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs uppercase tracking-[.25em] text-[#b8ff39]">Playground</p><h1 className="mt-3 text-4xl font-black">Reset your attention.</h1><p className="mt-4 max-w-xl text-[#91a39a]">Short interactive loops for focus and cognitive reset. Scores stay in your browser demo.</p></div><div className="flex gap-2"><button onClick={()=>{setMode('focus');reset()}} className={`rounded-full px-4 py-2 text-xs font-semibold ${mode==='focus'?'bg-[#b8ff39] text-black':'border border-white/10'}`}>Focus burst</button><button onClick={()=>{setMode('memory');reset()}} className={`rounded-full px-4 py-2 text-xs font-semibold ${mode==='memory'?'bg-[#b8ff39] text-black':'border border-white/10'}`}>Memory grid</button></div></div><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_.35fr]"><section className="glass relative h-[520px] overflow-hidden rounded-3xl"><div className="absolute left-5 top-5 text-xs text-[#607168]">{mode==='focus'?'FIND THE SIGNAL':'SEQUENCE LOCK'}</div>{mode==='focus'?<button disabled={time<=0} onClick={hitFocus} style={{left:`${target}%`,top:`${20+(score*17)%65}%`}} className="absolute h-16 w-16 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#b8ff39] text-xl text-black shadow-[0_0_35px_rgba(184,255,57,.6)] transition-all disabled:opacity-30">✦</button>:<div className="absolute inset-0 grid place-items-center"><div className="grid grid-cols-3 gap-3">{sequence.map((n,i)=><button key={`${n}-${i}`} onClick={()=>hitMemory(n)} className="h-20 w-20 rounded-2xl border border-[#b8ff39]/20 bg-[#b8ff39]/5 text-2xl font-black text-[#b8ff39] transition hover:scale-105 hover:bg-[#b8ff39]/15">{n}</button>)}</div></div>}<div className="absolute bottom-8 left-0 right-0 text-center"><p className="text-sm text-[#91a39a]">{message}</p></div></section><aside className="glass rounded-3xl p-7"><p className="text-xs text-[#607168]">TIME LEFT</p><p className="mt-2 text-6xl font-black text-[#b8ff39]">{time}s</p><p className="mt-6 text-xs text-[#607168]">SCORE</p><p className="mt-1 text-3xl font-black">{score}</p><div className="mt-8 space-y-3 text-sm text-[#91a39a]"><p>⚡ Attention reset</p><p>🧠 Cognitive loop</p><p>🔒 Nothing is stored</p></div><button onClick={reset} className="mt-8 w-full rounded-xl border border-white/10 px-4 py-3 text-sm">Restart</button></aside></div></main></Shell>}
